name: Deploy QA
on:
  push:
    branches:
      - 'Production' 
  workflow_dispatch:


jobs:
  deploy:
    runs-on: "Invex Apps Prod"
    env:
      REACT_APP_DB_USER: ${{ secrets.REACT_APP_DB_USER_PROD }}
      REACT_APP_DB_PASSWORD: ${{ secrets.REACT_APP_DB_PASSWORD_PROD }}
      REACT_APP_DB_HOST: ${{ secrets.REACT_APP_DB_HOST_PROD }}
      REACT_APP_DB_PORT: ${{ secrets.REACT_APP_DB_PORT_PROD }}
      REACT_APP_DB_NAME: ${{ secrets.REACT_APP_DB_NAME_PROD }}
      REACT_APP_Server_Port: ${{ secrets.REACT_APP_Server_Port_PROD }}
      REACT_APP_CLEO_PATH: ${{ secrets.REACT_APP_CLEO_PATH_PROD }}

    steps:
      # 1.  Get the code
      - uses: actions/checkout@v4.2.2
      

      # 2. Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
        shell: cmd

      # 3. Stop any previous instance (ignore if not running)
      - name: Stop old process
        run: |
          try {
            npx pm2 kill
          } catch {
            Write-Host "No PM2 processes to stop"
          }
        shell: powershell
        continue-on-error: true

      # 4. Start with PM2
      - name: Launch with PM2
        run: |
          $env:RUNNER_TRACKING_ID=""
          $env:PM2_FORCE_WIN32="1"
          $env:PIDUSAGE_USE_PS="1"
          npx pm2 start ecosystem.config.cjs --update-env
          npx pm2 save
        shell: powershell

      # 5. Verify deployment
      - name: Check PM2 status
        run: npx pm2 reload all --update-env
        shell: cmd
