name: Trigger auto deployment for edi-frontend-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ PROD-Containerization-CHG0022027 ]
    paths:
    - '**'
    - '.github/workflows/edi-frontend-prod-AutoDeployTrigger-bdcf7c68-1cbb-429c-8c94-1aa2c4775d5f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.EDIFRONTENDPROD_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: azstprod-d3bua9bvbddcegbh.azurecr.io
          registryUsername: ${{ secrets.EDIFRONTENDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EDIFRONTENDPROD_REGISTRY_PASSWORD }}
          containerAppName: edi-frontend-prod
          resourceGroup: az-cld-edi-prod-rg
          imageToBuild: azstprod-d3bua9bvbddcegbh.azurecr.io/edi-frontend-prod:${{ github.sha }}
          
            

     

