name: Print Secrets

on:
  push:
    branches: 
      [ BackendContainer ]

    
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret Values
        run: |
          echo "VOUCHER_SERVICE_URL (base64):"
          echo "${{ secrets.VOUCHER_SERVICE_URL }}" || base64
          echo ""
          
          echo "REACT_APP_API_URL (base64):"
          echo "${{ secrets.REACT_APP_API_URL }}"  || base64
          echo ""
          
          echo "REACT_APP_CLIENT_ID (base64):"
          echo "${{ secrets.REACT_APP_CLIENT_ID }}" || base64
          echo ""
          
          echo "REACT_APP_CLIENT_SECRET (base64):"
          echo "${{ secrets.REACT_APP_CLIENT_SECRET }}" || base64
          echo ""
          
          echo "REACT_APP_AS400_URL (base64):"
          echo "${{ secrets.REACT_APP_AS400_URL }}" || base64
          echo ""
          
          echo "REACT_APP_AS400_USER (base64):"
          echo "${{ secrets.REACT_APP_AS400_USER }}" || base64
          echo ""
          
          echo "REACT_APP_AS400_PASSWORD (base64):"
          echo "${{ secrets.REACT_APP_AS400_PASSWORD }}" || base64
          echo ""
          
          echo "REACT_APP_AS400_SERVER (base64):"
          echo "${{ secrets.REACT_APP_AS400_SERVER }}" || base64
          echo ""
          
          echo "REACT_APP_AS400_LIBRARY (base64):"
          echo "${{ secrets.REACT_APP_AS400_LIBRARY }}" || base64
